# Constants used in the project

ELEM_TYPE_TO_IDX = {'ENTITY': 0, 'EVENT': 1, 'BOTH': 2, 'TIMEX3': 3}
IDX_TO_ELEM_TYPE = ['ENTITY', 'EVENT', 'BOTH', 'TIMEX3']

DUPLICATE_START_TAG = '<DUPLICATE>'
DUPLICATE_END_TAG = '</DUPLICATE>'
